    
pipeline {
    agent any
    stages {
        stage("build") {
            steps {
                cleanWs()
                checkout scm
                sh '''
                   cd boxfuse-sample-java-war-hello-master/
                   mvn package
                '''
            }
        }
    }
 }
