    
pipeline {
    agent any
    stages {
        stage("build") {
            steps {
                cleanWs()
                checkout scm
                sh '''
                   cd boxfuse-sample-java-war-hello-master/
                   mvn package
                '''
            }
        }
        stage("Deploy")
        {
            steps{
                sh '''
                cp boxfuse-sample-java-war-hello-master/target/hello-1.0.war /opt/tomcat/webapps/
                sudo systemctl stop tomcat
                sudo systemctl start tomcat
                '''
            }
        }
    }
 }
