    
pipeline {
    agent any
    stages {
        stage("build") {
            steps {
                cleanWs()
                checkout scm
                sh '''
                   cd boxfuse-sample-java-war-hello-master/
                   mvn package
                '''
            }
        }
        stage("Deploy")
        {
            steps{
                sh '''
                sudo rm -rf /opt/tomcat/webapps/hello-1.0*               
                sudo cp boxfuse-sample-java-war-hello-master/target/hello-1.0.war boxfuse-sample-java-war-hello-master/
                sudo docker build -f boxfuse-sample-java-war-hello-master/Dockerfile -t .
                '''
            }
        }
    }
 }
